### ISSUE TITLE
对比实验的一些疑问

### ISSUE THREAD

**Issue by 21-10-4** [xianlin7/SAMUS#13]
![image](https://github.com/xianlin7/SAMUS/assets/91857689/ef6054fc-4455-4e6c-99e1-d2ae826ae7e9)

请问，SAM，MedSAM，SAMed，MSA有在US30K数据集上训练微调吗？还是说，使用了各自项目作者提供的权重，在US30K的测试集上直接跑的结果？期待您的回答。

**Comment by 21-10-4** [comment]
还是说，除了SAM，其他的MedSAM，SAMed，MSA有在US30K数据集上训练微调？

**Comment by xianlin7** [comment]
> ![image](https://private-user-images.githubusercontent.com/91857689/316420326-ef6054fc-4455-4e6c-99e1-d2ae826ae7e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTQwMTIsIm5iZiI6MTcxMTM1MzcxMiwicGF0aCI6Ii85MTg1NzY4OS8zMTY0MjAzMjYtZWY2MDU0ZmMtNDQ1NS00ZTZjLTk5ZTEtZDJhZTgyNmFlN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA4MDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTcwMjk0ZjJjNTQ1ZTJhODJlNzA4MjE5YjE4YzdjYWFjMDk3NzYxYzRmY2Q1ZGJmN2I4NmE3MjE5MjE3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQuqVnKZRUaq7NyK_g9l45CVw4UlvDEExCfvP8e_frw)
> 
> 请问，SAM，MedSAM，SAMed，MSA有在US30K数据集上训练微调吗？还是说，使用了各自项目作者提供的权重，在US30K的测试集上直接跑的结果？期待您的回答。

你好，感谢对SAMUS的关注。对比实验全部根据原文设置，在US30K上进行了微调。

**Comment by 21-10-4** [comment]
感谢您的回答
