### ISSUE TITLE
论文图表序号问题

### ISSUE THREAD

**Issue by Zehui-Lin** [xianlin7/SAMUS#16]
Arxiv版本论文，论文图表序号好像有些问题。
例如文章中提到的Fig.8和Table 6好像都是不对应的。

**Comment by Zehui-Lin** [comment]
论文中出现了两次References，最后一页和Appendix前各出现一次

**Comment by xianlin7** [comment]
> Arxiv版本论文，论文图表序号好像有些问题。 例如文章中提到的Fig.8和Table 6好像都是不对应的。

感谢您的提醒，我们会在最终版本中检查是否存在类似问题。
