### ISSUE TITLE
关于SAMUS效果问题

### ISSUE THREAD

**Issue by Zehui-Lin** [xianlin7/SAMUS#17]
为什么模型在'US30K'数据集训练得到精度效果，没有单个数据集的高？按理说，数据量更多更丰富，模型的泛化性更好，性能也更高才是，而且US30K里面也包含了单个数据集，请问这种现象该如何解释呢？

**Comment by xianlin7** [comment]
> 为什么模型在'US30K'数据集训练得到精度效果，没有单个数据集的高？按理说，数据量更多更丰富，模型的泛化性更好，性能也更高才是，而且US30K里面也包含了单个数据集，请问这种现象该如何解释呢？

因为单个数据集上训练是专攻对应任务，训练出来的参数会更加拟合（甚至过拟合）到这个任务上。就像让一个人学习18门差异很大的课程和专门学习1门课一样，学习18门课学识更渊博，在其他领域也能表现出色，但是学习一门课就可以只针对这门课深入挖掘。当然，如果18门课程之间差异很小的话，学习的知识本质上有一些联系，那么还是有可能会超过专攻一门课的。

因为我们的US30K数据集之间差异很大，特别是对于那些训练数据量占比相对小的任务而言，它学到的来自其他任务的知识比自己的知识还多，而且其他任务的知识和自己需要的知识差异性比较大，性能就不如只单独在自己任务上学习的效果好。

**Comment by Zehui-Lin** [comment]
谢谢你的回答！
