### ISSUE TITLE
some questions about "example_of_required_dataset_format/US30K/MainPatient/train. txt" 

### ISSUE THREAD

**Issue by Sagacity1125** [xianlin7/SAMUS#2]
"example_of_required_dataset_format/US30K/MainPatient/train. txt" content is as follow:
`1/Breast-BUSI/benign0046

1/ThyroidNodule-TN3K/trainval0001

1/ThyroidNodule-TG3K/trainval0000

1/Echocardiography-CAMUS/0055_2CH_000

2/Echocardiography-CAMUS/0055_2CH_000

3/Echocardiography-CAMUS/0055_2CH_000`

But I don't understand what the first number 1/2/3 means. Please explain the content in detail. Looking forward to your reply!!!
Thank you!!!

**Comment by xianlin7** [comment]
The first number 1/2/3 represents the class ID on the label. For example, there are 13 categories in the BTCV dataset, then 1 represents the spleen, 2 represents the right kidney, 3 represents the left kidney, etc. By introducing the class ID, we can generate the corresponding masks from labels easily.

**Comment by yxddzho** [comment]
我怎么确定每个图的类别呢

**Comment by xianlin7** [comment]
> 我怎么确定每个图的类别呢

类别ID就是每个数据集里面每个类别的标签值。

**Comment by yxddzho** [comment]
您好，如果是二分类的话，就是1吗



---Original---
From: "Xian ***@***.***&gt;
Date: Mon, Mar 25, 2024 17:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [xianlin7/SAMUS] some questions about"example_of_required_dataset_format/US30K/MainPatient/train. txt"  (Issue #2)




  
我怎么确定每个图的类别呢
  
类别ID就是每个数据集里面每个类别的标签值。
