### ISSUE TITLE
Data split

### ISSUE THREAD

**Issue by marwankefah** [xianlin7/SAMUS#3]
Hi, 

I came across your work and found it impressive.

I'm eager to reproduce those results and conduct a detailed comparison. So, I was wondering if you could do me a favor and share the data splits (train, val, test) you used in your study. Having access to the same data splits would be incredibly valuable in ensuring an accurate replication.

Best regards,
Marawan Elbatel

**Comment by atalay-korkut** [comment]
Did you get the data splits?

**Comment by marwankefah** [comment]
Yes, you may refer to the respective papers of the datasets, they divide it already.
