### ISSUE TITLE
Some issue for requirement.txt

### ISSUE THREAD

**Issue by LI-CHIN-CHIA** [xianlin7/SAMUS#4]
老铁，为何我没办法安装requirement.txt，他出现
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\home\\ktietz\\src\\ci\\alabaster_1611921544520\\work'

**Comment by xianlin7** [comment]
你有把requirement.txt放到'C:\home\ktietz\src\ci\alabaster_1611921544520\work'目录下吗？
需要cd到对应目录下安装。

**Comment by LI-CHIN-CHIA** [comment]
您好 我想请问这个资料夹我需要自己创建还是本来就有的

Xian Lin ***@***.***>於 2023年10月7日 週六，下午8:02寫道：

**Comment by xianlin7** [comment]
这个应该是你原本就有的。你需要下载整个SAMUS文件到你指定的目录，然后cd到SAMUS所在目录下，再安装requirement.txt里的各个包。

**Comment by huoyiru** [comment]
你好，请问我在服务器上运行代码，没有ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/ktietz/src/ci/alabaster_1611921544520/work'相关的路径我应该如何运行代码呢

**Comment by TobyZhouWei** [comment]
您好, 我对您的工作非常感兴趣, 您在requirement.txt中引用了您的绝对路径, 由于工作环境不同, 导致无法直接使用pip install 命令.您是否可以进行修改, 以便确保环境的完整, 感谢!!

**Comment by xianlin7** [comment]
> 你好，请问我在服务器上运行代码，没有ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/ktietz/src/ci/alabaster_1611921544520/work'相关的路径我应该如何运行代码呢

我已更新requirement.txt文件，可以下载后重新安装

**Comment by xianlin7** [comment]
> 您好, 我对您的工作非常感兴趣, 您在requirement.txt中引用了您的绝对路径, 由于工作环境不同, 导致无法直接使用pip install 命令.您是否可以进行修改, 以便确保环境的完整, 感谢!!

感谢您的提醒，我已更新可以直接使用的requirement.txt文件

**Comment by LI-CHIN-CHIA** [comment]
> > 您好, 我对您的工作非常感兴趣, 您在requirement.txt中引用了您的绝对路径, 由于工作环境不同, 导致无法直接使用pip install 命令.您是否可以进行修改, 以便确保环境的完整, 感谢!!
> 
> 感谢您的提醒，我已更新可以直接使用的requirement.txt文件

非常感谢您，祝有个愉快的十一假期

**Comment by LI-CHIN-CHIA** [comment]
您好，我想请问在使用该代码时，是使用ubuntu还是windows系统呢?

**Comment by xianlin7** [comment]
> 您好，我想请问在使用该代码时，是使用ubuntu还是windows系统呢?

ubuntu
